import type { Metadata } from "next";
import { ReactNode } from 'react';
import { Inter } from 'next/font/google';
import { CharacterProvider } from '@/context/CharacterContext'; // Importa tu proveedor de contexto

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Knights',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Envuelve los elementos con el proveedor de contexto */}
        <CharacterProvider>
          {children}
        </CharacterProvider>
      </body>
    </html>
  );
}

